import Image from 'next/image'
import React from 'react'

export default function BloagContent() {
    return (
        <div className="md:px-4 my-8">
            <div className="container px-4 md:px-0 m-auto flex flex-col md:items-center lg:px-28 xl:px-36 2xl:px-48">
                <div className="heading text-2xl md:text-3xl font-bold self-start">Lorem ipsum dolor sit amet consectetur adipisicing.</div>
                <div className="para mb-8 md:mb-10 mt-4 ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut autem delectus assumenda, iure eaque natus, dolorem earum soluta eos perferendis accusamus officia ipsum quis, ea aut repellendus nobis quo temporibus corporis molestias ad laudantium!</div>
                <Image src="/w-1.png" width={800} height={800} />
                <div className="content space-y-6 mt-6">
                    <div className="para">Lorem ipsum dolor sit amet consectetur adipisicing elit. In deserunt repellendus ex dolor tenetur doloribus, veniam, enim delectus nemo beatae minus. Modi, odio, assumenda placeat itaque dolorem repellendus minus aspernatur atque aut ullam ratione ipsum cum autem! Consectetur, laborum inventore odio eos sit hic quos, possimus nostrum accusamus cumque maxime, at aspernatur nulla dignissimos minus voluptas quibusdam ea quidem illo incidunt enim voluptatibus! Incidunt molestiae est nemo aspernatur ad in iure neque voluptate. Nisi asperiores ea impedit mollitia saepe animi illum harum hic maiores iste itaque minima, rem repudiandae ipsa veritatis fuga nostrum laboriosam minus qui alias incidunt totam. Alias nesciunt fugiat cum. Magni corrupti doloribus nesciunt soluta facere cum, vero minima dicta minus laborum error rerum odit aliquam reprehenderit illo ex iusto sapiente necessitatibus sunt labore? Deserunt nisi aspernatur doloremque in fugiat eligendi voluptatum soluta. Vel earum facere sit et consectetur eos impedit eum voluptatum animi dolorum tempora id vero quasi maxime aliquid officia laboriosam, vitae cum porro quod dolore. Similique magnam fugit eaque voluptatibus voluptas. Nulla temporibus quia eius labore iure ipsa reprehenderit aut accusantium, aliquid, debitis aspernatur a delectus non, molestiae quod laudantium est illum dolores assumenda. Odio facere harum veritatis praesentium amet veniam aliquid eveniet architecto.</div>

                    <div className="para">Lorem ipsum dolor sit amet consectetur adipisicing elit. In deserunt repellendus ex dolor tenetur doloribus, veniam, enim delectus nemo beatae minus. Modi, odio, assumenda placeat itaque dolorem repellendus minus aspernatur atque aut ullam ratione ipsum cum autem! Consectetur, laborum inventore odio eos sit hic quos, possimus nostrum accusamus cumque maxime, at aspernatur nulla dignissimos minus voluptas quibusdam ea quidem illo incidunt enim voluptatibus! Incidunt molestiae est nemo aspernatur ad in iure neque voluptate. Nisi asperiores ea impedit mollitia saepe animi illum harum hic maiores iste itaque minima, rem repudiandae ipsa veritatis fuga nostrum laboriosam minus qui alias incidunt totam. Alias nesciunt fugiat cum. Magni corrupti doloribus nesciunt soluta facere cum, vero minima dicta minus laborum error rerum odit aliquam reprehenderit illo ex iusto sapiente necessitatibus sunt labore? Deserunt nisi aspernatur doloremque in fugiat eligendi voluptatum soluta. Vel earum facere sit et consectetur eos impedit eum voluptatum animi dolorum tempora id vero quasi maxime aliquid officia laboriosam, vitae cum porro quod dolore. Similique magnam fugit eaque voluptatibus voluptas. Nulla temporibus quia eius labore iure ipsa reprehenderit aut accusantium, aliquid, debitis aspernatur a delectus non, molestiae quod laudantium est illum dolores assumenda. Odio facere harum veritatis praesentium amet veniam aliquid eveniet architecto.</div>
                </div>
            </div>
        </div>
    )
}
